### PR TITLE
Add a table comparing RVA and RVB

### PR DESCRIPTION
**Pull request by rpsene**
This update enhances the documentation by providing a clear and organized comparison of the RVA and RVB extensions, making it easier for developers and stakeholders to understand the differences and requirements.

- Added a new table to the documentation that provides a detailed comparison between the RVA23U64, RVA23S64, RVB23U64, and RVB23S64 extensions.
- Sorted the entries alphabetically and updated the numbering for clarity and consistency.

### CODE REVIEW

**Comment by rpsene** [comment]
@kasanovic @aswaterman please, double check each line. I did went thorough rva and and rvb multiple times, but I'm not 100% confident that I captured it precisely.

**Comment by james-ball-qualcomm** [comment]
Can we add another view of this information that just shows the differences between RVA23 and RVB23? I still want this even though they are split into 2 separate OpaVotes.

**Comment by aswaterman** [comment]
RVA and RVB are really separate beasts, and so linking them together in the form of a table doesn’t make much sense to me. I’ll scan the table for fact-checking purposes, but I won’t be the one to approve the PR.

**Comment by james-ball-qualcomm** [comment]
I'm asking for another view of the table that omits rows that are the same between RVA23 and RVB23. Make sense?

**Comment by james-ball-qualcomm** [comment]
I don't care if it gets approved in a pull request. I just want to see the information.

**Comment by aswaterman** [comment]
The only bugs I spotted in the table are that Zicond and Zcmop are missing.

**Comment by james-ball-qualcomm** [comment]
I don't see the H extension (mandatory in RVA23, expansion option in RVB23) mentioned. Also, when H is present, there are several other extensions like Ssstateen, Shcounterenw, etc. that become mandatory but I don't see those mentioned in the table either.

**Comment by rpsene** [comment]
@james-ball-qualcomm H and its dependencies are on the table.

image

**Comment by james-ball-qualcomm** [comment]
I don't see H or its friends in the table sent out by Jeff about an hour ago. Is his table incorrect/incomplete/out-of-date?

Screenshot 2024-08-21 165126
[RVA23 vs RVB23 Differences.pdf](https://github.com/user-attachments/files/16700960/RVA23.vs.RVB23.Differences.pdf)

**Comment by rpsene** [comment]
> I don't see H or its friends in the table sent out by Jeff about an hour ago. Is his table incorrect/incomplete/out-of-date?
> 
> 
> 
> Screenshot 2024-08-21 165126
> 
> [RVA23 vs RVB23 Differences.pdf](https://github.com/user-attachments/files/16700960/RVA23.vs.RVB23.Differences.pdf)
> 
> 

@james-ball-qualcomm I shared a complete version *before* the email was sent. If you check the Google Sheet, it is fully updated.

**Comment by james-ball-qualcomm** [comment]
I don't see any email from you sharing a complete version before Jeff's email went out. Also, what do you mean the Google Sheet? All I'm aware of is this ASCIIDOC table in this GitHub and then a PDF that Jeff mailed out. Is there also a Google Sheet?

**Comment by james-ball-qualcomm** [comment]
I'm sending you a meeting request so we can discuss this live and clear it up quickly.

**Pull request closed without merging**
